INSTRUMENT_DATABASE = [
    {
        "id": "ipaq",
        "name": "IPAQ",
        "full_name": "International Physical Activity Questionnaire",
        "area": "Educação Física / Saúde Pública",
        "construct": "Nível de atividade física",
        "objective_keywords": [
            "atividade física",
            "nível de atividade física",
            "sedentarismo",
            "exercício físico",
            "comportamento sedentário",
        ],
        "original_reference": {
            "authors": "Craig CL et al.",
            "year": 2003,
            "title": "International Physical Activity Questionnaire: 12-country reliability and validity",
            "journal": "Medicine & Science in Sports & Exercise",
            "doi": "10.1249/01.MSS.0000078924.61453.FB",
        },
        "brazilian_validation_reference": {
            "authors": "Matsudo S, Araújo T, Matsudo V, Andrade D, Andrade E, Oliveira LC, Braggion G",
            "year": 2001,
            "title": "Questionário Internacional de Atividade Física (IPAQ): estudo de validade e reprodutibilidade no Brasil",
            "journal": "Revista Brasileira de Atividade Física & Saúde",
            "doi": "10.12820/rbafs.v.6n2p5-18",
        },
        "validated_population_brazil": "Adultos brasileiros; há estudos específicos com jovens adultos e idosos.",
        "license_use": "Uso acadêmico geralmente permitido, mas recomenda-se utilizar a versão oficial e citar o protocolo.",
        "scoring": "Calcula minutos/semana de caminhada, atividade moderada e vigorosa. Pode classificar em sedentário, irregularmente ativo, ativo ou muito ativo conforme protocolo IPAQ.",
        "application_mode": ["questionário presencial", "questionário online", "entrevista"],
        "ethical_notes": [
            "Baixo risco.",
            "Pode gerar constrangimento leve sobre hábitos de vida.",
            "Indicar tempo estimado de preenchimento.",
        ],
    },
    {
        "id": "whoqol_bref",
        "name": "WHOQOL-bref",
        "full_name": "World Health Organization Quality of Life - Bref",
        "area": "Saúde / Qualidade de vida",
        "construct": "Qualidade de vida",
        "objective_keywords": [
            "qualidade de vida",
            "saúde percebida",
            "bem-estar",
            "percepção de saúde",
        ],
        "original_reference": {
            "authors": "The WHOQOL Group",
            "year": 1998,
            "title": "Development of the World Health Organization WHOQOL-BREF quality of life assessment",
            "journal": "Psychological Medicine",
            "doi": "10.1017/S0033291798006667",
        },
        "brazilian_validation_reference": {
            "authors": "Fleck MPA et al.",
            "year": 2000,
            "title": "Aplicação da versão em português do instrumento abreviado de avaliação da qualidade de vida WHOQOL-bref",
            "journal": "Revista de Saúde Pública",
            "doi": "10.1590/S0034-89102000000200012",
        },
        "validated_population_brazil": "Adultos brasileiros em diferentes contextos de saúde.",
        "license_use": "Instrumento da OMS; usar versão autorizada/oficial e seguir orientações de uso.",
        "scoring": "26 itens em escala Likert de 1 a 5. Gera escores nos domínios físico, psicológico, relações sociais e meio ambiente. Quanto maior o escore, melhor a qualidade de vida.",
        "application_mode": ["questionário presencial", "questionário online", "entrevista"],
        "ethical_notes": [
            "Baixo risco.",
            "Pode abordar aspectos subjetivos de saúde e bem-estar.",
            "Garantir sigilo das respostas.",
        ],
    },
    {
        "id": "psqi",
        "name": "PSQI",
        "full_name": "Pittsburgh Sleep Quality Index",
        "area": "Sono / Saúde",
        "construct": "Qualidade do sono",
        "objective_keywords": [
            "sono",
            "qualidade do sono",
            "insônia",
            "distúrbio do sono",
            "recuperação",
        ],
        "original_reference": {
            "authors": "Buysse DJ, Reynolds CF, Monk TH, Berman SR, Kupfer DJ",
            "year": 1989,
            "title": "The Pittsburgh Sleep Quality Index: a new instrument for psychiatric practice and research",
            "journal": "Psychiatry Research",
            "doi": "10.1016/0165-1781(89)90047-4",
        },
        "brazilian_validation_reference": {
            "authors": "Bertolazi AN et al.",
            "year": 2011,
            "title": "Validation of the Brazilian Portuguese version of the Pittsburgh Sleep Quality Index",
            "journal": "Sleep Medicine",
            "doi": "10.1016/j.sleep.2010.04.020",
        },
        "validated_population_brazil": "Adultos brasileiros; há estudos em populações clínicas e adolescentes.",
        "license_use": "Verificar permissão de uso da versão oficial antes da aplicação.",
        "scoring": "19 itens autoaplicáveis agrupados em 7 componentes, cada um de 0 a 3. Escore global de 0 a 21; valores acima de 5 indicam pior qualidade do sono.",
        "application_mode": ["questionário presencial", "questionário online"],
        "ethical_notes": [
            "Baixo risco.",
            "Pode revelar informações de saúde e rotina pessoal.",
            "Garantir confidencialidade.",
        ],
    },
    {
        "id": "dass_21",
        "name": "DASS-21",
        "full_name": "Depression, Anxiety and Stress Scale - 21",
        "area": "Psicologia / Saúde Mental",
        "construct": "Sintomas de depressão, ansiedade e estresse",
        "objective_keywords": [
            "ansiedade",
            "depressão",
            "estresse",
            "saúde mental",
            "sintomas emocionais",
        ],
        "original_reference": {
            "authors": "Lovibond PF, Lovibond SH",
            "year": 1995,
            "title": "The structure of negative emotional states: comparison of the Depression Anxiety Stress Scales with the Beck Depression and Anxiety Inventories",
            "journal": "Behaviour Research and Therapy",
            "doi": "10.1016/0005-7967(94)00075-U",
        },
        "brazilian_validation_reference": {
            "authors": "Vignola RCB, Tucci AM",
            "year": 2014,
            "title": "Adaptation and validation of the Depression, Anxiety and Stress Scale (DASS) to Brazilian Portuguese",
            "journal": "Journal of Affective Disorders",
            "doi": "10.1016/j.jad.2013.10.031",
        },
        "validated_population_brazil": "Adultos brasileiros; há estudos adicionais com adolescentes e amostras clínicas.",
        "license_use": "Disponível em versões oficiais; verificar orientação dos autores e da página DASS antes de uso comercial.",
        "scoring": "21 itens, escala de 0 a 3. Soma-se cada subescala: depressão, ansiedade e estresse. Em geral, os escores da versão curta são multiplicados por 2 para equivalência com a DASS-42.",
        "application_mode": ["questionário presencial", "questionário online"],
        "ethical_notes": [
            "Risco moderado quando aplicado em saúde mental.",
            "Prever encaminhamento em caso de sofrimento psicológico relevante.",
            "Não usar como diagnóstico clínico isolado.",
        ],
    },
    {
        "id": "sas_2",
        "name": "SAS-2",
        "full_name": "Sport Anxiety Scale-2",
        "area": "Psicologia do Esporte",
        "construct": "Ansiedade-traço competitiva",
        "objective_keywords": [
            "ansiedade esportiva",
            "ansiedade competitiva",
            "atletas",
            "competição",
            "ansiedade no esporte",
        ],
        "original_reference": {
            "authors": "Smith RE, Smoll FL, Cumming SP, Grossbard JR",
            "year": 2006,
            "title": "Measurement of multidimensional sport performance anxiety in children and adults: The Sport Anxiety Scale-2",
            "journal": "Journal of Sport and Exercise Psychology",
            "doi": "10.1123/jsep.28.4.479",
        },
        "brazilian_validation_reference": {
            "authors": "Silva-Rocha VV, Osório FL",
            "year": 2017,
            "title": "Cross-cultural adaptation of the Sport Anxiety Scale-2 (SAS-2) for the Brazilian context",
            "journal": "Trends in Psychiatry and Psychotherapy",
            "doi": "10.1590/2237-6089-2017-0027",
        },
        "validated_population_brazil": "Atletas brasileiros profissionais e amadores; estudo psicométrico com 238 atletas.",
        "license_use": "Verificar autorização de uso da escala original e da versão brasileira.",
        "scoring": "15 itens distribuídos em três subescalas: ansiedade somática, preocupação e perturbação da concentração. Cada subescala possui 5 itens; maiores escores indicam maior ansiedade esportiva.",
        "application_mode": ["questionário presencial", "questionário online"],
        "ethical_notes": [
            "Pode gerar desconforto ao abordar ansiedade competitiva.",
            "Não utilizar como diagnóstico clínico.",
            "Prever orientação/encaminhamento se houver sofrimento significativo.",
        ],
    },
    {
        "id": "csai_2",
        "name": "CSAI-2",
        "full_name": "Competitive State Anxiety Inventory-2",
        "area": "Psicologia do Esporte",
        "construct": "Ansiedade-estado competitiva",
        "objective_keywords": [
            "ansiedade pré-competitiva",
            "ansiedade competitiva",
            "estado de ansiedade",
            "autoconfiança",
            "competição esportiva",
        ],
        "original_reference": {
            "authors": "Martens R, Vealey RS, Burton D",
            "year": 1990,
            "title": "Competitive Anxiety in Sport",
            "journal": "Human Kinetics",
            "doi": None,
        },
        "brazilian_validation_reference": {
            "authors": "Coelho EM, Vasconcelos-Raposo J, Mahl AC",
            "year": 2010,
            "title": "Confirmatory factorial analysis of the Brazilian version of the Competitive State Anxiety Inventory-2",
            "journal": "Spanish Journal of Psychology",
            "doi": "10.1017/S1138741600003776",
        },
        "validated_population_brazil": "Atletas brasileiros; estudos posteriores analisam estrutura interna em amostras de atletas de diferentes modalidades.",
        "license_use": "Verificar autorização/licença, pois é instrumento originalmente associado a material publicado.",
        "scoring": "Tradicionalmente avalia ansiedade cognitiva, ansiedade somática e autoconfiança. Itens em escala Likert; calcular subescalas conforme manual/versão utilizada.",
        "application_mode": ["questionário presencial"],
        "ethical_notes": [
            "Aplicar preferencialmente em contexto esportivo controlado.",
            "Pode gerar desconforto pré-competitivo.",
            "Explicar que os dados não interferem em escalação ou avaliação técnica.",
        ],
    },
    {
        "id": "bsq",
        "name": "BSQ",
        "full_name": "Body Shape Questionnaire",
        "area": "Imagem corporal / Saúde",
        "construct": "Preocupação com forma corporal",
        "objective_keywords": [
            "imagem corporal",
            "insatisfação corporal",
            "forma corporal",
            "preocupação com corpo",
            "transtorno alimentar",
        ],
        "original_reference": {
            "authors": "Cooper PJ, Taylor MJ, Cooper Z, Fairburn CG",
            "year": 1987,
            "title": "The development and validation of the Body Shape Questionnaire",
            "journal": "International Journal of Eating Disorders",
            "doi": "10.1002/1098-108X(198707)6:4<485::AID-EAT2260060405>3.0.CO;2-O",
        },
        "brazilian_validation_reference": {
            "authors": "Conti MA, Cordás TA, Latorre MRDO",
            "year": 2009,
            "title": "A study of the validity and reliability of the Brazilian version of the Body Shape Questionnaire among adolescents",
            "journal": "Revista Brasileira de Saúde Materno Infantil",
            "doi": "10.1590/S1519-38292009000300012",
        },
        "validated_population_brazil": "Adolescentes brasileiros; há estudos com universitários.",
        "license_use": "Verificar permissão de uso e versão aplicável.",
        "scoring": "Versão clássica com 34 itens em escala de 1 a 6. Escore total de 34 a 204; maiores valores indicam maior preocupação com a forma corporal.",
        "application_mode": ["questionário presencial", "questionário online"],
        "ethical_notes": [
            "Risco moderado quando envolve imagem corporal e possível sofrimento psicológico.",
            "Cuidado com adolescentes e populações vulneráveis.",
            "Evitar linguagem que induza julgamento corporal.",
        ],
    },
    {
        "id": "abq",
        "name": "ABQ",
        "full_name": "Athlete Burnout Questionnaire",
        "area": "Psicologia do Esporte",
        "construct": "Burnout em atletas",
        "objective_keywords": [
            "burnout",
            "esgotamento",
            "atletas",
            "exaustão",
            "desvalorização esportiva",
        ],
        "original_reference": {
            "authors": "Raedeke TD, Smith AL",
            "year": 2001,
            "title": "Development and preliminary validation of an athlete burnout measure",
            "journal": "Journal of Sport and Exercise Psychology",
            "doi": "10.1123/jsep.23.4.281",
        },
        "brazilian_validation_reference": {
            "authors": "Guedes DP, Souza RO, et al.",
            "year": 2016,
            "title": "Psychometric properties of the Athlete Burnout Questionnaire for young Brazilian athletes",
            "journal": "Journal of Physical Education",
            "doi": "10.4025/jphyseduc.v27i1.2708",
        },
        "validated_population_brazil": "Jovens atletas brasileiros; há estudo posterior com jovens e adultos atletas.",
        "license_use": "Verificar autorização de uso da escala.",
        "scoring": "15 itens distribuídos em três dimensões: exaustão emocional/física, reduzido senso de realização e desvalorização esportiva. Maiores escores indicam maior burnout.",
        "application_mode": ["questionário presencial", "questionário online"],
        "ethical_notes": [
            "Pode revelar sofrimento psicológico no esporte.",
            "Prever encaminhamento quando houver alto esgotamento.",
            "Não usar isoladamente como diagnóstico clínico.",
        ],
    },
    {
        "id": "borg_rpe",
        "name": "Escala de Borg",
        "full_name": "Rating of Perceived Exertion",
        "area": "Exercício físico / Treinamento",
        "construct": "Percepção subjetiva de esforço",
        "objective_keywords": [
            "percepção de esforço",
            "intensidade do exercício",
            "carga de treino",
            "esforço",
            "treinamento",
        ],
        "original_reference": {
            "authors": "Borg G",
            "year": 1982,
            "title": "Psychophysical bases of perceived exertion",
            "journal": "Medicine & Science in Sports & Exercise",
            "doi": "10.1249/00005768-198205000-00012",
        },
        "brazilian_validation_reference": {
            "authors": "Não há uma única validação brasileira universal; há ampla utilização em estudos nacionais de exercício físico.",
            "year": None,
            "title": "Verificar estudo específico conforme população e protocolo.",
            "journal": None,
            "doi": None,
        },
        "validated_population_brazil": "Amplamente utilizada em adultos, idosos, atletas e populações clínicas; escolher referência conforme população.",
        "license_use": "Verificar versão específica da escala e direitos de reprodução.",
        "scoring": "Pode usar escala 6–20 ou CR10. O participante indica a percepção subjetiva de esforço; maiores valores indicam maior intensidade percebida.",
        "application_mode": ["presencial", "durante exercício", "pós-sessão"],
        "ethical_notes": [
            "Baixo risco.",
            "Em intervenção física, associar a critérios de interrupção e segurança.",
            "Não substitui monitoramento clínico quando necessário.",
        ],
    },
    {
        "id": "eva_dor",
        "name": "EVA",
        "full_name": "Escala Visual Analógica de Dor",
        "area": "Dor / Saúde",
        "construct": "Intensidade subjetiva de dor",
        "objective_keywords": [
            "dor",
            "intensidade da dor",
            "desconforto",
            "percepção de dor",
        ],
        "original_reference": {
            "authors": "Huskisson EC",
            "year": 1974,
            "title": "Measurement of pain",
            "journal": "The Lancet",
            "doi": "10.1016/S0140-6736(74)90884-8",
        },
        "brazilian_validation_reference": {
            "authors": "Instrumento amplamente utilizado no Brasil; selecionar referência específica conforme população clínica.",
            "year": None,
            "title": "Verificar validação conforme contexto de aplicação.",
            "journal": None,
            "doi": None,
        },
        "validated_population_brazil": "Diversas populações; uso comum em adultos, idosos e contextos clínicos.",
        "license_use": "Geralmente livre, mas verificar versão gráfica utilizada.",
        "scoring": "Linha geralmente de 10 cm ou escala de 0 a 10. Zero representa ausência de dor; 10 representa pior dor imaginável.",
        "application_mode": ["presencial", "online com adaptação cuidadosa"],
        "ethical_notes": [
            "Baixo a moderado risco dependendo do contexto clínico.",
            "Se houver dor intensa, prever encaminhamento ou interrupção da coleta/intervenção.",
        ],
    },
]
